version: '2.1'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_HOST: "localhost"
      MYSQL_DATABASE: "godevdb"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=secret --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 10

  app:
    container_name: app
    build: .
    ports:
      - "1323:1323"
    depends_on:
      mysql:
        condition: service_healthy